### ISSUE TITLE
有没有准备搞个中文版的sc-gpt

### ISSUE THREAD

**Issue by wind91725** [pengbaolin/SC-GPT#10]
您好，现在中文也有CrossWOZ数据集，是否有想法搞个中文版的sc-gpt呢？我自己拿CrossWOZ数据集训练了下，最终验证集loss稳定在1左右，我想请问下，您在再训练时，dev集的loss大概是多少呀？

**Comment by pengbaolin** [comment]
暂时没有计划做中文版。loss取决于数据集，如果没有记错，5个epoch后loss大约1-3左右。
