### ISSUE TITLE
Could you update the file of train.py?

### ISSUE THREAD

**Issue by kiseliu** [pengbaolin/SC-GPT#11]
I think there has a problem in TextSeqDataset Class.  Why label = tokenized_text? I think it should be label = tokenized_text[:-1] + [50256] if we ignore the padding part.

**Comment by pengbaolin** [comment]
eos_token has already been appended. Please refer to line 112.

**Comment by kiseliu** [comment]
Sorry, I update the issue,  I think it should be label = tokenized_text[1:] + [50256].
