### ISSUE TITLE
evaluator.py script for attraction/train/taxi 

### ISSUE THREAD

**Issue by WenTingTseng** [pengbaolin/SC-GPT#17]
Hello，I want to ask about where is the evaluator.py script for attraction/train/taxi .
When I run evaluator.py script it always appear "ValueError: 'a.request ' is not in list"
error message.How can I solve it.

Thanks a lot for your help

**Comment by mriganktiwari** [comment]
I have been trying for a evaluator.py version for another domain of my own data.
If anybody has worked it out, I would appreciate help as well.

**Comment by pengbaolin** [comment]
I started working on this project again. Will post the scripts asap.
