### ISSUE TITLE
pre-training dataset source

### ISSUE THREAD

**Issue by HanNight** [pengbaolin/SC-GPT#3]
Can you tell me whether the MultiWOZ corpus used in the dataset is 1.0 or 2.0? And if possible, also tell me the source of the other three datasets in case I uesd the wrong dataset. Thanks!

**Comment by mrcmoresi** [comment]
I have the same questions as HanNight. Also I want to know if the released checkpoint was fined tunned on the three datasets and MultiWOZ?

**Comment by pengbaolin** [comment]
The multiwoz dataset we used is 2.0. The other datasets can be found on the web e.g. https://github.com/google-research/google-research/tree/master/schema_guided_dst.  and facebook data repo

The released checkpoint was not finetuend on multiwoz.

**Comment by mriganktiwari** [comment]
> Can you tell me whether the MultiWOZ corpus used in the dataset is 1.0 or 2.0? And if possible, also tell me the source of the other three datasets in case I uesd the wrong dataset. Thanks!

Hi @HanNight, did you figure out the way to use dialogue act based data for pre-training. Please help if you have any pre-processing script for those. I am looking to pre train a different version of gpt2 in the pattern mentioned in this paper.
