### ISSUE TITLE
No files in folder transformers

### ISSUE THREAD

**Issue by ZiteHe** [pengbaolin/SC-GPT#4]
Traceback (most recent call last):
  File "generate.py", line 13, in <module>
    from transformers import GPT2Config, OpenAIGPTConfig, XLNetConfig, TransfoXLConfig, XLMConfig, CTRLConfig
ImportError: cannot import name 'GPT2Config' from 'transformers' (unknown location)

**Comment by pengbaolin** [comment]
hi can you follow the requirement.txt to install transformers==2.1.1 ?
