### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by wind91725** [pengbaolin/SC-GPT#5]
您好，非常感谢您发布这个项目。我想请问下，这个项目根本上来说就是对GPT2的调优？
先基于GPT2预训练模型对大量 意图槽值格式-自然语言格式 的数据进行再训练。
然后就可以对小样本数据进行finetune，是这个意思吗？

**Comment by rl15442** [comment]
> 您好，非常感谢您发布这个项目。我想请问下，这个项目根本上来说就是对GPT2的调优？
> 先基于GPT2预训练模型对大量 意图槽值格式-自然语言格式 的数据进行再训练。
> 然后就可以对小样本数据进行finetune，是这个意思吗？

你好 老哥有兴趣加个微信（lovestoryRR）讨论讨论吗 我最近也在做这个任务

**Comment by pengbaolin** [comment]
对，是这个意思。
