### ISSUE TITLE
中文数据不收敛

### ISSUE THREAD

**Issue by wind91725** [pengbaolin/SC-GPT#6]
您好，我用中文的数据按照您的数据格式 去训练，发现不收敛，请问您知道是什么原因吗？

**Comment by kangbrilliant** [comment]
@wind91725  有兴趣沟通一下吗 我也做这个任务

**Comment by rl15442** [comment]
老哥有兴趣加个微信（lovestoryRR）沟通一下吗 我最近正在做nlg的transfer learning

**Comment by pengbaolin** [comment]
你好，我们预训练没有在中文上做过，可能是这样原因导致中文小数据不收敛。
