### ISSUE TITLE
加了--eval_all_checkpoints 程序跑不了

### ISSUE THREAD

**Issue by rl15442** [pengbaolin/SC-GPT#7]
python train.py --output_dir=‘ouput_dir’ --model_type=bert --model_name_or_path '2nd_General_TinyBERT_4L_312D/' --mlm --do_train --do_eval --eval_data_file=data/restaurant/train.txt --per_gpu_train_batch_size 1  --num_train_epochs 5  --learning_rate 5e-5      --overwrite_cache  --use_tokenize --train_data_file=data/restaurant/train.txt --overwrite_output_dir --eval_all_checkpoints

你好 为啥我加了加了--eval_all_checkpoints 这个之后老是报错啊

**Comment by pengbaolin** [comment]
请调试相关函数，适配模型命名结构。
